-- Cached Google Keyword Planner metrics and related ideas. Browser clients have
-- no direct access; the portal's authenticated server API reads these rows.
create table if not exists public.seo_keyword_research (
  id bigint generated by default as identity primary key,
  keyword text not null,
  country_code text not null,
  country text not null,
  language_code text not null default 'en',
  source text not null,
  monthly_searches bigint,
  competition text,
  competition_index integer,
  low_top_page_bid_micros bigint,
  high_top_page_bid_micros bigint,
  monthly_search_volumes jsonb not null default '[]'::jsonb,
  captured_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (keyword, country_code)
);

create index if not exists seo_keyword_research_volume_idx
  on public.seo_keyword_research (monthly_searches desc nulls last);

alter table public.seo_keyword_research enable row level security;
revoke all on public.seo_keyword_research from anon, authenticated;
