-- Private SEO visibility history. All browser access goes through the same-origin
-- server API; the service-role key is never exposed to the portal.
create table if not exists public.seo_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null,
  location_name text not null default 'United Kingdom',
  language_code text not null default 'en',
  device text not null default 'desktop' check (device in ('desktop', 'mobile')),
  target_url text,
  tag text,
  page_title text,
  source_path text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (keyword, location_name, device)
);

create table if not exists public.seo_rank_snapshots (
  id bigint generated by default as identity primary key,
  keyword_id bigint not null references public.seo_keywords(id) on delete cascade,
  checked_at timestamptz not null,
  organic_position numeric,
  ranking_url text,
  result_type text,
  serp_depth integer not null,
  result_count integer,
  cost_usd numeric,
  created_at timestamptz not null default now(),
  unique (keyword_id, checked_at)
);

create table if not exists public.seo_gsc_daily (
  id bigint generated by default as identity primary key,
  row_key text not null unique,
  search_date date not null,
  query text not null,
  page text not null default '',
  device text not null default '',
  country text not null default '',
  clicks numeric not null default 0,
  impressions numeric not null default 0,
  ctr numeric not null default 0,
  position numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seo_collection_runs (
  id uuid primary key,
  provider text not null,
  started_at timestamptz not null,
  finished_at timestamptz,
  status text not null check (status in ('running', 'complete', 'partial', 'failed')),
  items_requested integer not null default 0,
  items_succeeded integer not null default 0,
  cost_usd numeric not null default 0,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists seo_rank_snapshots_keyword_checked_idx
  on public.seo_rank_snapshots (keyword_id, checked_at desc);
create index if not exists seo_gsc_daily_date_idx
  on public.seo_gsc_daily (search_date desc);
create index if not exists seo_gsc_daily_query_idx
  on public.seo_gsc_daily (query);

alter table public.seo_keywords enable row level security;
alter table public.seo_rank_snapshots enable row level security;
alter table public.seo_gsc_daily enable row level security;
alter table public.seo_collection_runs enable row level security;

revoke all on public.seo_keywords from anon, authenticated;
revoke all on public.seo_rank_snapshots from anon, authenticated;
revoke all on public.seo_gsc_daily from anon, authenticated;
revoke all on public.seo_collection_runs from anon, authenticated;
